Numpy Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg
between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Pandas Questions <br>
5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0). <br>
`df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')` <br>
6. Replace missing values in Min.Price and Max.Price columns with
their respective mean. <br>
`df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')` <br>
7. How to get the rows of a dataframe with row sum > 100? <br>`df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))`

In [1]:
import numpy as np

In [23]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[5, 6, 7], [7, 8, 9]])

print(np.vstack((A, B)))
print(np.hstack((A, B)))

[[1 2 3]
 [3 4 5]
 [5 6 7]
 [7 8 9]]
[[1 2 3 5 6 7]
 [3 4 5 7 8 9]]


In [24]:
print(np.intersect1d(A, B))

[5]


In [25]:
print(A[np.where((A >= 3) & (A <= 10))])

[3 3 4 5]


In [26]:
website = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(website, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

print(data[(data[:, 2] > 1.5) & (data[:, 0] < 5.0)])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.head)

<bound method NDFrame.head of    Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passe

In [29]:
print(df.loc[::20, ['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [31]:
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)


print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


/var/folders/yn/s1tkm5xx3cs6xz1k8pl0jc780000gn/T/ipykernel_89967/129616807.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
/var/folders/yn/s1tkm5xx3cs6xz1k8pl0jc780000gn/T/ipykernel_89967/129616807.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting v

In [32]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df[df.sum(axis=1) > 100])

     0   1   2   3
2   30  29  37  16
3   11  34  24  38
5   21  38  26  30
6   24  29  38  15
7   37  17  18  35
8   31  23  24  32
9   36  31  36  37
10  16  32  17  37
13  37  13  36  20
